import { Injectable } from '@angular/core';
import { ServicesModule } from '../services.module';
import { AuditlogInfo } from './auditlog-info';
import { Observable, of } from 'rxjs';

@Injectable({
  providedIn: ServicesModule
})
export class AuditlogService {

  constructor() { }

  getAuditlogs(): Observable<AuditlogInfo[]> {
    return of(AuditLogList);
  }
}


export const AuditLogList: AuditlogInfo[] = [
  {
    Id: 1,
    BrowserInfo: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36',
    ClientIpAddress: '127.0.0.1',
    ClientName: '',
    CustomData: '',
    Exception: '',
    ExecutionDuration: '10',
    ExecutionTime: '2020-06-10 01:00:43',
    ImpersonatorTenantId: '',
    ImpersonatorUserId: '',
    MethodName: 'GetAllAsync',
    Parameters: '{"input":{"keyword":null,"isActive":null,"skipCount":0,"maxResultCount":10}}',
    ServiceName: 'CommodityRetail.MultiTenancy.TenantAppService',
    TenantId: '',
    UserId: '1',
    ReturnValue: '',
  },
  {
    Id: 2,
    BrowserInfo: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36',
    ClientIpAddress: '127.0.0.1',
    ClientName: '',
    CustomData: '',
    Exception: '',
    ExecutionDuration: '10',
    ExecutionTime: '2020-06-10 01:00:43',
    ImpersonatorTenantId: '',
    ImpersonatorUserId: '',
    MethodName: 'GetAllAsync',
    Parameters: '{"input":{"keyword":null,"isActive":null,"skipCount":0,"maxResultCount":10}}',
    ServiceName: 'CommodityRetail.MultiTenancy.TenantAppService',
    TenantId: '',
    UserId: '1',
    ReturnValue: '',
  },
  {
    Id: 3,
    BrowserInfo: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36',
    ClientIpAddress: '127.0.0.1',
    ClientName: '',
    CustomData: '',
    Exception: '',
    ExecutionDuration: '10',
    ExecutionTime: '2020-06-10 01:00:43',
    ImpersonatorTenantId: '',
    ImpersonatorUserId: '',
    MethodName: 'GetAllAsync',
    Parameters: '{"input":{"keyword":null,"isActive":null,"skipCount":0,"maxResultCount":10}}',
    ServiceName: 'CommodityRetail.MultiTenancy.TenantAppService',
    TenantId: '',
    UserId: '1',
    ReturnValue: '',
  },
  {
    Id: 4,
    BrowserInfo: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36',
    ClientIpAddress: '127.0.0.1',
    ClientName: '',
    CustomData: '',
    Exception: '',
    ExecutionDuration: '10',
    ExecutionTime: '2020-06-10 01:00:43',
    ImpersonatorTenantId: '',
    ImpersonatorUserId: '',
    MethodName: 'GetAllAsync',
    Parameters: '{"input":{"keyword":null,"isActive":null,"skipCount":0,"maxResultCount":10}}',
    ServiceName: 'CommodityRetail.MultiTenancy.TenantAppService',
    TenantId: '',
    UserId: '1',
    ReturnValue: '',
  },
  {
    Id: 5,
    BrowserInfo: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36',
    ClientIpAddress: '127.0.0.1',
    ClientName: '',
    CustomData: '',
    Exception: 'error',
    ExecutionDuration: '10',
    ExecutionTime: '2020-06-10 01:00:43',
    ImpersonatorTenantId: '',
    ImpersonatorUserId: '',
    MethodName: 'GetAllAsync',
    Parameters: '{"input":{"keyword":null,"isActive":null,"skipCount":0,"maxResultCount":10}}',
    ServiceName: 'CommodityRetail.MultiTenancy.TenantAppService',
    TenantId: '',
    UserId: '1',
    ReturnValue: '',
  },
  {
    Id: 6,
    BrowserInfo: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36',
    ClientIpAddress: '127.0.0.1',
    ClientName: '',
    CustomData: '',
    Exception: '',
    ExecutionDuration: '10',
    ExecutionTime: '2020-06-10 01:00:43',
    ImpersonatorTenantId: '',
    ImpersonatorUserId: '',
    MethodName: 'GetAllAsync',
    Parameters: '{"input":{"keyword":null,"isActive":null,"skipCount":0,"maxResultCount":10}}',
    ServiceName: 'CommodityRetail.MultiTenancy.TenantAppService',
    TenantId: '',
    UserId: '1',
    ReturnValue: '',
  },
  {
    Id: 7,
    BrowserInfo: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36',
    ClientIpAddress: '127.0.0.1',
    ClientName: '',
    CustomData: '',
    Exception: '',
    ExecutionDuration: '10',
    ExecutionTime: '2020-06-10 01:00:43',
    ImpersonatorTenantId: '',
    ImpersonatorUserId: '',
    MethodName: 'GetAllAsync',
    Parameters: '{"input":{"keyword":null,"isActive":null,"skipCount":0,"maxResultCount":10}}',
    ServiceName: 'CommodityRetail.MultiTenancy.TenantAppService',
    TenantId: '',
    UserId: '1',
    ReturnValue: '',
  },
  {
    Id: 8,
    BrowserInfo: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36',
    ClientIpAddress: '127.0.0.1',
    ClientName: '',
    CustomData: '',
    Exception: '',
    ExecutionDuration: '10',
    ExecutionTime: '2020-06-10 01:00:43',
    ImpersonatorTenantId: '',
    ImpersonatorUserId: '',
    MethodName: 'GetAllAsync',
    Parameters: '{"input":{"keyword":null,"isActive":null,"skipCount":0,"maxResultCount":10}}',
    ServiceName: 'CommodityRetail.MultiTenancy.TenantAppService',
    TenantId: '',
    UserId: '1',
    ReturnValue: '',
  },
  {
    Id: 9,
    BrowserInfo: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36',
    ClientIpAddress: '127.0.0.1',
    ClientName: '',
    CustomData: '',
    Exception: '',
    ExecutionDuration: '10',
    ExecutionTime: '2020-06-10 01:00:43',
    ImpersonatorTenantId: '',
    ImpersonatorUserId: '',
    MethodName: 'GetAllAsync',
    Parameters: '{"input":{"keyword":null,"isActive":null,"skipCount":0,"maxResultCount":10}}',
    ServiceName: 'CommodityRetail.MultiTenancy.TenantAppService',
    TenantId: '',
    UserId: '1',
    ReturnValue: '',
  },
  {
    Id: 10,
    BrowserInfo: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36',
    ClientIpAddress: '127.0.0.1',
    ClientName: '',
    CustomData: '',
    Exception: 'error',
    ExecutionDuration: '10',
    ExecutionTime: '2020-06-10 01:00:43',
    ImpersonatorTenantId: '',
    ImpersonatorUserId: '',
    MethodName: 'GetAllAsync',
    Parameters: '{"input":{"keyword":null,"isActive":null,"skipCount":0,"maxResultCount":10}}',
    ServiceName: 'CommodityRetail.MultiTenancy.TenantAppService',
    TenantId: '',
    UserId: '1',
    ReturnValue: '',
  },
  {
    Id: 11,
    BrowserInfo: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36',
    ClientIpAddress: '127.0.0.1',
    ClientName: '',
    CustomData: '',
    Exception: '',
    ExecutionDuration: '10',
    ExecutionTime: '2020-06-10 01:00:43',
    ImpersonatorTenantId: '',
    ImpersonatorUserId: '',
    MethodName: 'GetAllAsync',
    Parameters: '{"input":{"keyword":null,"isActive":null,"skipCount":0,"maxResultCount":10}}',
    ServiceName: 'CommodityRetail.MultiTenancy.TenantAppService',
    TenantId: '',
    UserId: '1',
    ReturnValue: '',
  },
  {
    Id: 12,
    BrowserInfo: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36',
    ClientIpAddress: '127.0.0.1',
    ClientName: '',
    CustomData: '',
    Exception: '',
    ExecutionDuration: '10',
    ExecutionTime: '2020-06-10 01:00:43',
    ImpersonatorTenantId: '',
    ImpersonatorUserId: '',
    MethodName: 'GetAllAsync',
    Parameters: '{"input":{"keyword":null,"isActive":null,"skipCount":0,"maxResultCount":10}}',
    ServiceName: 'CommodityRetail.MultiTenancy.TenantAppService',
    TenantId: '',
    UserId: '1',
    ReturnValue: '',
  },
  {
    Id: 13,
    BrowserInfo: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36',
    ClientIpAddress: '127.0.0.1',
    ClientName: '',
    CustomData: '',
    Exception: '',
    ExecutionDuration: '10',
    ExecutionTime: '2020-06-10 01:00:43',
    ImpersonatorTenantId: '',
    ImpersonatorUserId: '',
    MethodName: 'GetAllAsync',
    Parameters: '{"input":{"keyword":null,"isActive":null,"skipCount":0,"maxResultCount":10}}',
    ServiceName: 'CommodityRetail.MultiTenancy.TenantAppService',
    TenantId: '',
    UserId: '1',
    ReturnValue: '',
  },
  {
    Id: 14,
    BrowserInfo: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36',
    ClientIpAddress: '127.0.0.1',
    ClientName: '',
    CustomData: '',
    Exception: '',
    ExecutionDuration: '10',
    ExecutionTime: '2020-06-10 01:00:43',
    ImpersonatorTenantId: '',
    ImpersonatorUserId: '',
    MethodName: 'GetAllAsync',
    Parameters: '{"input":{"keyword":null,"isActive":null,"skipCount":0,"maxResultCount":10}}',
    ServiceName: 'CommodityRetail.MultiTenancy.TenantAppService',
    TenantId: '',
    UserId: '1',
    ReturnValue: '',
  },
  {
    Id: 15,
    BrowserInfo: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36',
    ClientIpAddress: '127.0.0.1',
    ClientName: '',
    CustomData: '',
    Exception: 'error',
    ExecutionDuration: '10',
    ExecutionTime: '2020-06-10 01:00:43',
    ImpersonatorTenantId: '',
    ImpersonatorUserId: '',
    MethodName: 'GetAllAsync',
    Parameters: '{"input":{"keyword":null,"isActive":null,"skipCount":0,"maxResultCount":10}}',
    ServiceName: 'CommodityRetail.MultiTenancy.TenantAppService',
    TenantId: '',
    UserId: '1',
    ReturnValue: '',
  },
];
